In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
# You can easily check that a newly created object is an ndarray, passing the new variable to the type() function.
type(a)

numpy.ndarray

In [10]:
# In order to know the associated dtype to the just created ndarray, you have to use the dtype attribute.
a.dtype

dtype('int64')

In [19]:
# The just-created array has one axis, and then its rank is 1, while its shape should be (3,1). To obtain
# these values from the corresponding array it is sufficient to use the ndim attribute for getting the axes, the
# size attribute to know the array length, and the shape attribute to get its shape.
print("Rank is :",a.ndim)
print("Size of array is:",a.size)
print("Shape of array is:",a.shape)

Rank is : 1
Size of array is: 3
Shape of array is: (3,)


In [ ]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])

In [21]:
print("The dtype is: ",b.dtype)
print("Rank is :",b.ndim)
print("Size of array is:",b.size)
print("Shape of array is:",b.shape)

The dtype is:  float64
Rank is : 2
Size of array is: 4
Shape of array is: (2, 2)


In [26]:
# This array has rank 2, since it has two axis, each of length 2.
# Another important attribute is itemsize, which can be used with ndarray objects. It defines the size
# in bytes of each item in the array, and data is the buffer containing the actual elements of the array. This
# second attribute is still not generally used, since to access the data within the array you will use the indexing
# mechanism that you will see in the next sections.
print("Size in bytes of each item in array is: ",b.itemsize)
print("The buffer containing the array is: ",b.data)

Size in bytes of each item in array is:  8
The buffer containing the array is:  <memory at 0x71b3599a6740>


In [32]:
# Create an Array
# To create a new array you can follow different paths. The most common is the one you saw in the previous
# section through a list or sequence of lists as arguments to the array() function.
c = np.array([[1, 2, 3],[4, 5, 6]])

In [34]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# The array() function in addition to the lists can accept even tuples and sequences of tuples.
d = np.array(((1, 2, 3),(4, 5, 6)))

In [36]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# and also, even sequences of tuples and lists interconnected make no difference.
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])

In [38]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Types of Data

In [39]:
g = np.array([['a', 'b'],['c', 'd']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [40]:
g.dtype

dtype('<U1')

In [41]:
g.dtype.name

'str32'

In [42]:
# Actually, you can explicitly define the dtype using the dtype option as argument of the function.
f = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

Intrinsic Creation of an Array

In [44]:
# The zeros() function, for example, creates a full array of zeros with dimensions defined by the shape argument. For example, to create a two-dimensional array 3x3:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
# while the ones() function creates an array full of ones in a very similar way.
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
# By default, the two functions have created arrays with float64 data type. A feature that will be
# particularly useful is arange(). This function generates NumPy arrays with numerical sequences that
# respond to particular rules depending on the passed arguments. For example, if you want to generate a
# sequence of values between 0 and 10, you will be passed only one argument to the function, that is the value
# with which you want to end the sequence.
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# It is also possible to generate a sequence of values with precise intervals between them. If the third
# argument of the arange() function is specified, this will represent the gap between a value and the next one
# in the sequence of values.
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [48]:
# In addition, this third argument can also be a float.
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [49]:
# But so far you have only created one-dimensional arrays. To generate two-dimensional arrays you can
# still continue to use the arange() function but combined with the reshape() function. This function divides
# a linear array in different parts in the manner specified by the shape argument.
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
# Another function very similar to arange() is linspace(). This function still takes as its first two
# arguments the initial and end values of the sequence, but the third argument, instead of specifying the
# distance between one element and the next, defines the number of elements into which we want the interval to be split.
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [52]:
# Finally, another method to obtain arrays already containing values is to fill them with random values.
# This is possible using the random() function of the numpy.random module. This function will generate an
# array with many elements as specified in the argument.
np.random.random(3)

array([0.90633792, 0.26877268, 0.89593281])

Basic Operations

Arithmetic Operators

In [3]:
a = np.arange(4)

In [4]:
a

array([0, 1, 2, 3])

In [5]:
a+4

array([4, 5, 6, 7])

In [6]:
a*2

array([0, 2, 4, 6])

In NumPy, these operations are element-wise,
that is, the operators are applied only between corresponding elements, namely, that occupy the same
position, so that at the end as a result there will be a new array containing the results in the same location of
the operands

In [7]:
b = np.arange(4,8)

In [8]:
b

array([4, 5, 6, 7])

In [9]:
a+b

array([ 4,  6,  8, 10])

In [10]:
a-b

array([-4, -4, -4, -4])

In [11]:
a*b

array([ 0,  5, 12, 21])

Moreover, these operators are also available for functions, provided that the value returned is a NumPy
array. For example, you can multiply the array with the sine or the square root of the elements of the array b.

In [12]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [13]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

Moving on to the multidimensional case, even here the arithmetic operators continue to operate
element-wise.

In [14]:
A = np.arange(0, 9).reshape(3, 3)

In [15]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
B = np.ones((3, 3))

In [17]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

The Matrix Product

The choice of operating element-wise is a peculiar aspect of the NumPy library. In fact in many other tools
for data analysis, the * operator is understood as matrix product when it is applied to two matrices. Using
NumPy, this kind of product is instead indicated by the dot() function. This operation is not element-wise.

In [19]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

The result at each position is the sum of the products between each element of the corresponding
row of the first matrix with the corresponding element of the corresponding column of the second matrix.

An alternative way to write the matrix product is to see the dot() function as an object’s function of one
of the two matrices.

In [20]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

I want to add that since the matrix product is not a commutative operation, then the order of the
operands is important. Indeed A * B is not equal to B * A.

In [21]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

Increment and Decrement Operators

In [5]:
a = np.arange(4)

In [6]:
a

array([0, 1, 2, 3])

In [7]:
a += 1

In [8]:
a

array([1, 2, 3, 4])

In [10]:
a -= 1

In [11]:
a

array([0, 1, 2, 3])

Actually, there is no such operators in Python, since there are no operators ++ or ––. To increase or decrease
the values you have to use operators such as += or –=. These operators are not different from those that we
saw earlier, except that instead of creating a new array with the results, they will reassign the results to the
same array.

In [13]:
# array([0, 1, 2, 3])
a+=4

In [14]:
a

array([4, 5, 6, 7])

In [15]:
a *= 2

In [16]:
a

array([ 8, 10, 12, 14])

Universal Functions (ufunc)

A universal function, generally called ufunc, is a function operating of an array in an element-by-element
fashion. This means that it is a function that acts individually on each single element of the input array to
generate a corresponding result in a new output array. At the end, you will obtain an array of the same size of
the input.
There are many mathematical and trigonometric operations that meet this definition, for example, the
calculation of the square root with sqrt(), the logarithm with log(), or the sin with sin().

In [17]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [18]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [19]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [20]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [21]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [22]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Aggregate Functions

Aggregate functions are those functions that perform an operation on a set of values, an array for example,
and produce a single result. Therefore, the sum of all the elements in an array is an aggregate function. Many
functions of this kind are implemented within the class ndarray.

In [23]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])

In [24]:
a.sum()

15.0

In [25]:
a.min()

0.3

In [26]:
a.max()

5.7

In [27]:
a.mean()

3.0

In [28]:
a.std()

2.0079840636817816

Indexing, Slicing, and Iterating