In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
# You can easily check that a newly created object is an ndarray, passing the new variable to the type() function.
type(a)

numpy.ndarray

In [10]:
# In order to know the associated dtype to the just created ndarray, you have to use the dtype attribute.
a.dtype

dtype('int64')

In [19]:
# The just-created array has one axis, and then its rank is 1, while its shape should be (3,1). To obtain
# these values from the corresponding array it is sufficient to use the ndim attribute for getting the axes, the
# size attribute to know the array length, and the shape attribute to get its shape.
print("Rank is :",a.ndim)
print("Size of array is:",a.size)
print("Shape of array is:",a.shape)

Rank is : 1
Size of array is: 3
Shape of array is: (3,)


In [ ]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])

In [21]:
print("The dtype is: ",b.dtype)
print("Rank is :",b.ndim)
print("Size of array is:",b.size)
print("Shape of array is:",b.shape)

The dtype is:  float64
Rank is : 2
Size of array is: 4
Shape of array is: (2, 2)


In [26]:
# This array has rank 2, since it has two axis, each of length 2.
# Another important attribute is itemsize, which can be used with ndarray objects. It defines the size
# in bytes of each item in the array, and data is the buffer containing the actual elements of the array. This
# second attribute is still not generally used, since to access the data within the array you will use the indexing
# mechanism that you will see in the next sections.
print("Size in bytes of each item in array is: ",b.itemsize)
print("The buffer containing the array is: ",b.data)

Size in bytes of each item in array is:  8
The buffer containing the array is:  <memory at 0x71b3599a6740>


In [32]:
# Create an Array
# To create a new array you can follow different paths. The most common is the one you saw in the previous
# section through a list or sequence of lists as arguments to the array() function.
c = np.array([[1, 2, 3],[4, 5, 6]])

In [34]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# The array() function in addition to the lists can accept even tuples and sequences of tuples.
d = np.array(((1, 2, 3),(4, 5, 6)))

In [36]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# and also, even sequences of tuples and lists interconnected make no difference.
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])

In [38]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Types of Data

In [39]:
g = np.array([['a', 'b'],['c', 'd']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [40]:
g.dtype

dtype('<U1')

In [41]:
g.dtype.name

'str32'

In [42]:
# Actually, you can explicitly define the dtype using the dtype option as argument of the function.
f = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

Intrinsic Creation of an Array

In [44]:
# The zeros() function, for example, creates a full array of zeros with dimensions defined by the shape argument. For example, to create a two-dimensional array 3x3:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
# while the ones() function creates an array full of ones in a very similar way.
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
# By default, the two functions have created arrays with float64 data type. A feature that will be
# particularly useful is arange(). This function generates NumPy arrays with numerical sequences that
# respond to particular rules depending on the passed arguments. For example, if you want to generate a
# sequence of values between 0 and 10, you will be passed only one argument to the function, that is the value
# with which you want to end the sequence.
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# It is also possible to generate a sequence of values with precise intervals between them. If the third
# argument of the arange() function is specified, this will represent the gap between a value and the next one
# in the sequence of values.
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [48]:
# In addition, this third argument can also be a float.
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [49]:
# But so far you have only created one-dimensional arrays. To generate two-dimensional arrays you can
# still continue to use the arange() function but combined with the reshape() function. This function divides
# a linear array in different parts in the manner specified by the shape argument.
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
# Another function very similar to arange() is linspace(). This function still takes as its first two
# arguments the initial and end values of the sequence, but the third argument, instead of specifying the
# distance between one element and the next, defines the number of elements into which we want the interval to be split.
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [52]:
# Finally, another method to obtain arrays already containing values is to fill them with random values.
# This is possible using the random() function of the numpy.random module. This function will generate an
# array with many elements as specified in the argument.
np.random.random(3)

array([0.90633792, 0.26877268, 0.89593281])

Basic Operations